apiVersion: v1
kind: Namespace
metadata:
  name: k8s-demo


apiVersion: v1
kind: Pod
metadata:
  name: fibo
  namespace: k8s-demo
  labels:
    app: fibo
spec:
  containers:
  - name: fibo
    image: sumitsaiwal/fibonacci_flask


apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fibo
  namespace: k8s-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fibo
  template:
    metadata:
      name: fibo
      labels:
        app: fibo
    spec:
      containers:
      - name: fibo
        image: sumitsaiwal/fibonacci_flask

